FROM mono:latest AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
#RUN dotnet restore
RUN msbuild -t:restore

# Copy everything else and build
COPY . .
RUN nuget restore aspnetapp2.csproj -SolutionDirectory ../ -Verbosity normal
RUN msbuild 

# Build runtime image
#FROM microsoft/dotnet:aspnetcore-runtime
#WORKDIR /app
#COPY --from=build-env /app/out .
#ENTRYPOINT ["dotnet", "aspnetapp2.dll"]
CMD [ "mono", "aspnetapp2.dll" ]